version: 2.1
orbs:
  node: circleci/node@6.1.0
jobs:
  test-and-cov:
    executor:
      name: node/default
      tag: "22"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: pnpm
      - run: pnpm run test
      - run: pnpm run cov:send
workflows:
  test-app:
    jobs:
      - test-and-cov
